I am trying to port the RM tests and ran into an issue where the webservices-tools.jar was not in runtime classpath and it throws NoClassDeffoundError. This is because com.sun.tools.ws.api.wsdl.TWSDLExtensionHandler lies in webservices-tools.jar and webservices.jar has a META-INF/services entry pointing to the above class which cannot be found at runtime. I have added an entry to Main.java which got me ahead. I added similar cases for WsitWS in Main.java though not tested it. Let me know if there is a better option for this?
svn path=/trunk/; revision=64